"""Instance identity and independent power-budget checks for the bundled cell.

The centroid expectations are fixed from the connectivity correspondence,
not generated by the mapper under test. Most tests need only gdstk; the FEM
tests share one bitcell mesh and skip when the thermal dependencies are absent.
"""

from dataclasses import replace
import json
from pathlib import Path
import sys

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
gdstk = pytest.importorskip("gdstk")

from gds import bitcell_mapping as mapping
from gds import techmap
from gds.read import flatten_by_layer
from gds.sources import _dims_um, extract_contacts
from spec.chip import SourceBox


REPO = Path(__file__).resolve().parents[1]
GDS_PATH = REPO / "data/sram22_64x22m4w22.gds"
EXPECTED_CENTERS = {
    "X0": (-0.26, -0.195),
    "X1": (-0.295, -0.985),
    "X2": (-0.26, -1.385),
    "X3": (-0.94, -1.3225),
    "X4": (-0.94, -0.2575),
    "X5": (-0.94, -0.595),
    "X6": (-0.94, -0.985),
    "X7": (-0.295, -0.595),
}
EXPECTED_CLASSES = {
    "X0": "access", "X1": "latch", "X2": "access", "X3": "parasitic",
    "X4": "parasitic", "X5": "pullup", "X6": "pullup", "X7": "latch",
}
# Deliberately unequal even within each class; symmetry cannot hide copying.
UNEQUAL_POWERS = {f"X{i}": (i + 1) * 1e-9 for i in range(8)}


@pytest.fixture(scope="module")
def bitcell_layers():
    library = gdstk.read_gds(str(GDS_PATH))
    cell = next(cell for cell in library.cells if cell.name == "sram_sp_cell")
    return flatten_by_layer(cell)


@pytest.fixture(scope="module")
def mapped_channels(bitcell_layers):
    return mapping.map_bitcell_channels(bitcell_layers)


def _assert_expected_identity(channels):
    assert len(channels) == 8
    assert {channel.instance for channel in channels} == set(EXPECTED_CENTERS)
    for channel in channels:
        assert _dims_um(channel.polygon)[:2] == pytest.approx(
            EXPECTED_CENTERS[channel.instance], abs=1e-9)
        assert channel.device_class == EXPECTED_CLASSES[channel.instance]
    parasitics = [channel for channel in channels if channel.device_class == "parasitic"]
    assert all(channel.drain == channel.source for channel in parasitics)


def test_actual_gds_matches_independent_instance_centroids(mapped_channels):
    _assert_expected_identity(mapped_channels)


def test_original_mask_connectivity_reproduces_runtime_instance_terminals(mapped_channels):
    from cases.verify_bitcell_mapping import verify

    # This re-extracts conductor/terminal relationships without consulting
    # the committed runtime manifest or using the centroid lookup table.
    independent = verify(GDS_PATH, REPO / "data/sram_sp_cell.spice")
    records = {record["instance"]: record for record in independent["channels"]}
    assert set(records) == set(EXPECTED_CENTERS)
    for channel in mapped_channels:
        record = records[channel.instance]
        (x0, y0), (x1, y1) = channel.polygon.bounding_box()
        assert (x0, y0, x1, y1) == pytest.approx(record["bbox_um"], abs=1e-9)
        for field in ("gate", "drain", "source", "body", "device_class"):
            assert getattr(channel, field) == record[field]


def test_mapping_ignores_polygon_order_start_vertex_and_winding(bitcell_layers):
    reordered = {}
    for spec, polygons in reversed(list(bitcell_layers.items())):
        reordered[spec] = []
        for polygon in reversed(polygons):
            points = list(polygon.points)[::-1]
            points = points[1:] + points[:1]
            reordered[spec].append(gdstk.Polygon(points, layer=spec[0], datatype=spec[1]))
    assert mapping.geometry_fingerprint(reordered) == mapping.geometry_fingerprint(bitcell_layers)
    _assert_expected_identity(mapping.map_bitcell_channels(reordered))


@pytest.mark.parametrize("spec", [techmap.POLY, techmap.LI1], ids=["gate", "wire"])
def test_changed_geometry_rejects_stale_mapping(bitcell_layers, spec):
    changed = {key: [polygon.copy() for polygon in polygons]
               for key, polygons in bitcell_layers.items()}
    changed[spec][0].translate(0.001, 0.0)
    with pytest.raises(ValueError, match="geometry.*verified instance map"):
        mapping.map_bitcell_channels(changed)


def test_changed_netlist_fingerprint_rejects_stale_mapping(bitcell_layers, tmp_path, monkeypatch):
    manifest = json.loads(mapping.MANIFEST.read_text())
    first_netlist = next(iter(manifest["netlist_sha256"]))
    manifest["netlist_sha256"][first_netlist] = "0" * 64
    stale_manifest = tmp_path / "stale_manifest.json"
    stale_manifest.write_text(json.dumps(manifest))
    monkeypatch.setattr(mapping, "MANIFEST", stale_manifest)
    with pytest.raises(ValueError, match="netlist changed"):
        mapping.map_bitcell_channels(bitcell_layers)


def test_changed_gds_port_semantics_reject_stale_mapping(bitcell_layers, tmp_path, monkeypatch):
    # Labels do not survive flatten_by_layer(). The complete source-file
    # digest must therefore protect BL/BR identity independently of polygons.
    manifest = json.loads(mapping.MANIFEST.read_text())
    manifest["source_gds_sha256"] = "0" * 64
    stale_manifest = tmp_path / "stale_ports.json"
    stale_manifest.write_text(json.dumps(manifest))
    monkeypatch.setattr(mapping, "MANIFEST", stale_manifest)
    with pytest.raises(ValueError, match="GDS/port labels changed"):
        mapping.map_bitcell_channels(bitcell_layers)


def test_sources_preserve_every_unequal_instance_power_and_identity(mapped_channels):
    sources = mapping.channel_sources_for(list(reversed(mapped_channels)), UNEQUAL_POWERS)
    assert len(sources) == 8
    assert {box.device for box, _ in sources} == set(EXPECTED_CENTERS)
    assert sum(box.power_uw for box, _ in sources) * 1e-6 == pytest.approx(sum(UNEQUAL_POWERS.values()))
    for box, polygon in sources:
        assert box.kind == "channel"
        assert (box.x_um, box.y_um) == pytest.approx(EXPECTED_CENTERS[box.device], abs=1e-9)
        assert box.power_uw * 1e-6 == pytest.approx(UNEQUAL_POWERS[box.device], rel=1e-14)
        actual_volume = polygon.area() * box.t_um * 1e-18
        assert box.power_density_w_per_m3 * actual_volume == pytest.approx(
            UNEQUAL_POWERS[box.device], rel=1e-12)


def test_symmetric_powers_keep_legacy_class_totals_without_losing_identity(mapped_channels):
    class_powers = {"access": 1e-9, "latch": 2e-9, "pullup": 3e-9, "parasitic": 0.0}
    powers = {name: class_powers[device_class] for name, device_class in EXPECTED_CLASSES.items()}
    sources = mapping.channel_sources_for(mapped_channels, powers)
    assert sum(box.power_uw for box, _ in sources) * 1e-6 == pytest.approx(12e-9)
    for box, _ in sources:
        assert box.power_uw * 1e-6 == pytest.approx(class_powers[EXPECTED_CLASSES[box.device]])


def test_zero_power_is_valid_for_every_instance(mapped_channels):
    sources = mapping.channel_sources_for(mapped_channels, dict.fromkeys(EXPECTED_CENTERS, 0.0))
    assert len(sources) == 8
    assert all(box.power_uw == 0.0 and box.power_density_w_per_m3 == 0.0 for box, _ in sources)


@pytest.mark.parametrize("problem", ["missing", "extra", "negative", "nan", "inf", "negative-inf"])
def test_invalid_power_dictionary_is_rejected(mapped_channels, problem):
    powers = dict(UNEQUAL_POWERS)
    if problem == "missing":
        powers.pop("X7")
    elif problem == "extra":
        powers["X8"] = 1e-9
    else:
        powers["X7"] = {"negative": -1e-9, "nan": float("nan"),
                        "inf": float("inf"), "negative-inf": -float("inf")}[problem]
    with pytest.raises(ValueError, match="names|finite and nonnegative"):
        mapping.channel_sources_for(mapped_channels, powers)


@pytest.mark.parametrize("problem", ["missing", "duplicate", "extra"])
def test_missing_duplicate_or_extra_channel_identity_is_rejected(mapped_channels, problem):
    changed = list(mapped_channels)
    if problem == "missing":
        changed.pop()
    elif problem == "duplicate":
        changed[-1] = replace(changed[-1], instance=changed[0].instance)
    else:
        changed.append(replace(changed[-1], instance="X8"))
    with pytest.raises(ValueError, match="exactly once"):
        mapping.channel_sources_for(changed, UNEQUAL_POWERS)


def test_nonrectangular_heat_source_is_rejected(mapped_channels):
    original = mapped_channels[0]
    (x0, y0), (x1, y1) = original.polygon.bounding_box()
    triangular = gdstk.Polygon([(x0, y0), (x1, y0), (x1, y1)])
    changed = [replace(original, polygon=triangular), *mapped_channels[1:]]
    with pytest.raises(ValueError, match="Nonrectangular source"):
        mapping.channel_sources_for(changed, UNEQUAL_POWERS)


def test_mirrored_two_by_two_array_preserves_each_instance(monkeypatch):
    from gds import tile_array as array

    monkeypatch.setattr(array, "GDS_PATH", str(GDS_PATH))
    _, window, sources, contacts = array.tile_array(2, 2)
    assert window == pytest.approx((0.0, 2.4, 0.0, 3.16))
    assert len(sources) == 32
    assert len({box.device for box, _ in sources}) == 32
    assert all(box.power_uw == 0.0 for box, _ in sources + contacts)
    source_by_name = {box.device: (box, polygon) for box, polygon in sources}
    for row in range(2):
        for col in range(2):
            prefix = f"r{row}c{col}_"
            assert {name[len(prefix):] for name in source_by_name if name.startswith(prefix)} == set(EXPECTED_CENTERS)
            for instance, (local_x, local_y) in EXPECTED_CENTERS.items():
                x = local_x + 1.2
                y = local_y + 1.58
                if col % 2:
                    x = 1.2 - x
                if row % 2:
                    y = 1.58 - y
                expected = (x + col * 1.2, y + row * 1.58)
                box, polygon = source_by_name[prefix + instance]
                assert (box.x_um, box.y_um) == pytest.approx(expected, abs=1e-9)
                assert _dims_um(polygon)[:2] == pytest.approx(expected, abs=1e-9)


@pytest.fixture(scope="module")
def bitcell_fem(bitcell_layers, mapped_channels, tmp_path_factory):
    pytest.importorskip("dolfinx")
    pytest.importorskip("gmsh")
    from mesh.gds_build import build_gds_3d_mesh
    from physics.coeffs import build_coeffs

    channel_sources = mapping.channel_sources_for(mapped_channels, UNEQUAL_POWERS)
    contacts = []
    for index, polygon in enumerate(extract_contacts(bitcell_layers)):
        cx, cy, width, length = _dims_um(polygon)
        box = SourceBox(device=f"co{index}", kind="contact", x_um=cx, y_um=cy,
                        z0_um=0.0, w_um=width, l_um=length,
                        t_um=techmap.LICON1_THICKNESS_UM, power_uw=0.0)
        contacts.append((box, polygon))
    mesh_data, registry = build_gds_3d_mesh(
        bitcell_layers, (-1.2, 0.0, -1.58, 0.0), sum(UNEQUAL_POWERS.values()),
        out_dir=str(tmp_path_factory.mktemp("mapped_bitcell_fem")), refine=2.0,
        renders=False, stack=techmap.FRONTSIDE_STACK,
        channel_sources=channel_sources, contact_sources=contacts,
    )
    _, _, q = build_coeffs(mesh_data.mesh, mesh_data.cell_tags, registry)
    return mesh_data, registry, q


def test_actual_fem_delivers_each_original_device_power(bitcell_fem):
    from post.budget import verify_device_source_powers

    mesh_data, registry, q = bitcell_fem
    report = verify_device_source_powers(mesh_data, registry, q, UNEQUAL_POWERS)
    assert set(report["per_device"]) == set(EXPECTED_CENTERS)
    assert report["meshed_total_w"] == pytest.approx(sum(UNEQUAL_POWERS.values()), rel=1e-9)
    for name, values in report["per_device"].items():
        assert values["assigned_w"] == pytest.approx(UNEQUAL_POWERS[name], rel=1e-12)
        assert values["meshed_w"] == pytest.approx(UNEQUAL_POWERS[name], rel=1e-9)


def test_fem_audit_rejects_swapped_powers_even_when_total_is_unchanged(bitcell_fem):
    import numpy as np
    import ufl
    from dolfinx.fem import Function, assemble_scalar, form
    from post.budget import verify_device_source_powers

    mesh_data, registry, q = bitcell_fem
    by_name = {region.source.device: region for region in registry.all()
               if region.source is not None and region.source.kind == "channel"}
    first, second = by_name["X0"], by_name["X2"]
    def volume(region):
        return region.source.w_um * region.source.l_um * region.source.t_um

    assert volume(first) == pytest.approx(volume(second), rel=1e-12)
    changed = Function(q.function_space)
    changed.x.array[:] = q.x.array
    tags = mesh_data.cell_tags
    for destination, origin in ((first, second), (second, first)):
        cells = tags.indices[tags.values == destination.tag_id]
        dofs = np.unique([changed.function_space.dofmap.cell_dofs(int(cell))[0] for cell in cells])
        changed.x.array[dofs] = origin.source.power_density_w_per_m3
    changed.x.scatter_forward()
    dx = ufl.Measure("dx", domain=mesh_data.mesh)
    assert assemble_scalar(form(changed * dx)) == pytest.approx(
        assemble_scalar(form(q * dx)), rel=1e-10)
    with pytest.raises(ValueError, match="X[02]: meshed power"):
        verify_device_source_powers(mesh_data, registry, changed, UNEQUAL_POWERS)


def test_fem_audit_rejects_extra_heat_outside_channel_regions(bitcell_fem):
    from dolfinx.fem import Function
    from post.budget import verify_device_source_powers

    mesh_data, registry, q = bitcell_fem
    changed = Function(q.function_space)
    changed.x.array[:] = q.x.array
    background = next(region for region in registry.all() if region.source is None)
    tags = mesh_data.cell_tags
    for cell in tags.indices[tags.values == background.tag_id]:
        changed.x.array[changed.function_space.dofmap.cell_dofs(int(cell))] = 1e9
    changed.x.scatter_forward()
    with pytest.raises(ValueError, match="Total mesh heat"):
        verify_device_source_powers(mesh_data, registry, changed, UNEQUAL_POWERS)
