"""Transient thermal response of the real bitcell to a compact-model-driven
workload turning on, then off: sustained duty-cycle-averaged active power
(same magnitude as cases/run_bitcell_compact.py's steady case) until Tmax
approaches steady state, then zero-source idle until it relaxes back near
ambient. Saves every step's full temperature field (not just Tmax) so
figures/animations can be re-rendered later without re-solving -- see
cases/render_transient_layers.py, which does exactly that for a
fixed-viewpoint isometric layer-stack GIF of the hot spot forming.
Every X0..X7 channel receives its own instance's compact-model power through
gds.bitcell_mapping, including asymmetric HOLD/READ/WRITE operating points.

The default power model is a validated transient-SPICE READ-1. In sustained
mode, each device and local layout resistor receives its integrated event heat
times the access rate. --interconnect none selects the former ideal-wire model.
`--instantaneous` follows the complete per-source electrical waveforms, using
their exact piecewise-linear energy integral over each thermal timestep.
The electrical and thermal timesteps are independent. Power is never scaled
from an instantaneous sample or shared by transistor class. DC/timing models
remain available explicitly with --power-model dc-surrogate.

This is one-way electrical-to-thermal coupling, not temperature feedback or
an extracted full-macro workload. See SPICE_TRANSIENT.md for assumptions.

The notebook polygon mesh is the default. --mesh-manifest reuses the exact
mesh generated by read_gds.ipynb; --mesh-method legacy --interconnect none
selects the old boxes.

Lateral boundaries are periodic in x/y by default, as in the compact steady
case. --lateral-bc insulating restores zero-flux sidewalls. Periodicity
repeats the same geometry and workload by translation, not reflection.

    python cases/run_bitcell_transient.py [--point read_1] [--row-hit-rate 1.0]
    python cases/run_bitcell_transient.py --point read_1 --instantaneous
"""

import argparse
import hashlib
import json
import math
import sys
import types
from pathlib import Path

import gdstk
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from gds import techmap
from gds.bitcell_mapping import channel_sources_for, map_bitcell_channels, mapping_revision
from gds.read import flatten_by_layer
from gds.sources import _dims_um, extract_contacts
from gds.spice_power import (ACCESS_ENERGY_MODEL_REVISION, SPICE_MODEL_REVISION,
                             NAMED_BIAS_POINTS, named_access_pulse, named_bias_point_power_w)
from gds.thermal_workload import SPICE_ACCESS_POINTS, THERMAL_POWER_REVISION, build_spice_workload
from mesh.gds_build import build_gds_3d_mesh
from mesh.sram import build_sram_mesh
from mesh.viz3d import render_temperature_xy_slice
from physics.coeffs import build_coeffs
from physics.device_sources import DeviceHeatSources
from post.budget import power_balance, print_power_balance, verify_device_source_powers
from post.access_energy import verify_access_source_energy
from post.metrics import tmax
from solve.transient import TransientHeatSolver
from spec.chip import BoundaryConditions, SourceBox

GDS_PATH = "data/sram22_64x22m4w22.gds"
CELL_NAME = "sram_sp_cell"

# Geometrically growing steps cover the diffusion/cooling response up to
# tens of milliseconds; this is a timestep schedule, not a measured time constant.
DT0_S = 1e-6      # 1us initial step
DT_RATIO = 1.4    # growth factor per step
N_ACTIVE_STEPS = 30   # reaches ~1e-6*(1.4^30-1)/0.4 ~ 60ms of active time -> near steady state
N_IDLE_STEPS = 30     # same schedule again for the relaxation back toward ambient
N_RENDER_FRAMES_PER_PHASE = 20  # frames picked at uniform Tmax increments, not uniform step index


def _dt_schedule(n_steps, dt0=DT0_S, ratio=DT_RATIO):
    dt = dt0
    for _ in range(n_steps):
        yield dt
        dt *= ratio


def spice_thermal_time_grid(trace, max_step_ps):
    """Uniform thermal steps spanning the WHOLE validated electrical event.

    The small final adjustment makes all steps equal, allowing matrix reuse;
    electrical samples are still integrated at their actual nonuniform times.
    """
    if not math.isfinite(max_step_ps) or max_step_ps <= 0:
        raise ValueError("--thermal-step-ps must be finite and positive")
    duration = float(trace.time_s[-1])
    if trace.time_s[0] != 0 or not math.isfinite(duration) or duration <= 0:
        raise ValueError("SPICE access must have a finite, positive span starting at zero")
    count = math.ceil(duration / (max_step_ps * 1e-12))
    if count > 100000:
        raise ValueError("Requested thermal step would exceed 100000 access steps")
    return np.linspace(0.0, duration, count + 1), duration / count


def build_bitcell_mesh(device_power_w, out_dir, *, mesh_method="notebook", mesh_manifest=None,
                       refine=1.0):
    if mesh_method == "notebook":
        case = build_sram_mesh(device_power_w, out_dir, renders=False, refine=refine,
                               manifest_path=mesh_manifest)
        xmin, ymin, xmax, ymax = case.manifest["process_model"]["domain_bbox_um"]
        return case.mesh_data, case.registry, (xmin, xmax, ymin, ymax)
    if mesh_method != "legacy" or mesh_manifest is not None:
        raise ValueError("Use mesh_method='notebook' for a saved notebook mesh, or 'legacy'")
    lib = gdstk.read_gds(GDS_PATH)
    cell = next(c for c in lib.cells if c.name == CELL_NAME)
    by_layer = flatten_by_layer(cell)
    (x0, y0), (x1, y1) = cell.bounding_box()
    window = (x0, x1, y0, y1)

    mapped_channels = map_bitcell_channels(by_layer)
    channel_sources = channel_sources_for(mapped_channels, device_power_w)

    contacts = extract_contacts(by_layer)
    contact_sources = [
        (SourceBox(device=f"co{i}", kind="contact", x_um=_dims_um(poly)[0], y_um=_dims_um(poly)[1],
                    z0_um=0.0, w_um=_dims_um(poly)[2], l_um=_dims_um(poly)[3],
                    t_um=techmap.LICON1_THICKNESS_UM, power_uw=0.0), poly)
        for i, poly in enumerate(contacts)
    ]

    total_power_w = max(sum(b.power_uw for b, _ in channel_sources) * 1e-6, 1e-18)
    mesh_data, registry = build_gds_3d_mesh(
        by_layer, window, total_power_w, out_dir=str(out_dir), refine=refine, renders=False,
        stack=techmap.FRONTSIDE_STACK, channel_sources=channel_sources, contact_sources=contact_sources,
    )
    return mesh_data, registry, window


def _select_uniform_dt_frames(tmax_hist, n_frames):
    """Sample accumulated temperature variation, always retaining extrema.

    Actual SPICE heating is nonmonotone: its hot peak may precede the end of
    the electrical observation window. Sampling only first-to-last temperature
    would omit that peak. Variation-based selection preserves chronology while
    still avoiding too many flat frames from a geometrically growing schedule.
    """
    t = np.asarray(tmax_hist)
    if n_frames < 2:
        raise ValueError("At least two frames per phase are required")
    if t.size == 0:
        return []
    distance = np.r_[0.0, np.cumsum(abs(np.diff(t)))]
    targets = np.linspace(0.0, distance[-1], n_frames)
    idx = [int(np.argmin(abs(distance - target))) for target in targets]
    return sorted(set(idx + [0, len(t)-1, int(np.argmax(t)), int(np.argmin(t))]))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--point", default="read_1", choices=sorted(set(SPICE_ACCESS_POINTS) | set(NAMED_BIAS_POINTS)))
    p.add_argument("--power-model", choices=["spice-transient", "dc-surrogate"], default="spice-transient")
    p.add_argument("--period-ns", type=float, help="repetition period for averaged SPICE power")
    p.add_argument("--pulse-width-ns", type=float, help="SPICE WL high plateau; default Liberty proxy")
    p.add_argument("--spice-step-ps", type=float, default=1.0, help="maximum electrical timestep")
    p.add_argument("--interconnect", choices=["layout", "none"], default=None,
                   help="layout-linked wire/contact Joule heat (default for SPICE); none reproduces ideal wires")
    p.add_argument("--interconnect-step-um", type=float, default=0.05,
                   help="maximum electrical sheet-network tile size, not thermal mesh size")
    p.add_argument("--thermal-step-ps", type=float, default=5.0,
                   help="maximum thermal timestep during one SPICE access (default 5 ps)")
    p.add_argument("--row-hit-rate", type=float, default=1.0,
                   help="sustained access frequency: 1.0=every cycle, 1/N_ROWS=uniform access")
    p.add_argument("--instantaneous", action="store_true",
                   help="one time-resolved SPICE access and cooldown, instead of sustained averaged power; "
                        "dc-surrogate mode instead uses an explicit rectangle")
    p.add_argument("--lateral-bc", choices=["periodic", "insulating"], default="periodic",
                   help="x/y boundary condition (default: periodic, same cell/activity repeated by translation)")
    p.add_argument("--out-dir", default=None, help="override the output directory for separate comparison runs")
    p.add_argument("--mesh-method", choices=["notebook", "legacy"], default="notebook")
    p.add_argument("--mesh-manifest", help="reuse a sealed notebook material_regions.json without remeshing")
    p.add_argument("--refine", type=float, default=1.0, help="mesh length multiplier; smaller means finer")
    p.add_argument("--no-renders", action="store_true", help="save temperature fields without plots/GIFs")
    args = p.parse_args()
    if args.power_model == "spice-transient" and args.point not in SPICE_ACCESS_POINTS:
        p.error("SPICE accesses are read_0/read_1/write_0_to_1/write_1_to_0; "
                "use --power-model dc-surrogate for crowbar/HOLD/settled-WRITE")
    if args.power_model == "dc-surrogate":
        if args.point not in NAMED_BIAS_POINTS:
            p.error("This point requires --power-model spice-transient")
        if (args.period_ns is not None or args.pulse_width_ns is not None
                or args.spice_step_ps != 1.0 or args.thermal_step_ps != 5.0):
            p.error("SPICE timing controls require --power-model spice-transient")
    if args.instantaneous and args.point == "hold_1":
        p.error("hold_1 is sustained leakage, not a single access; omit --instantaneous")
    if args.instantaneous and args.row_hit_rate != 1.0:
        p.error("--row-hit-rate applies only to sustained workloads, not one selected access")
    if not np.isfinite(args.row_hit_rate) or not 0.0 <= args.row_hit_rate <= 1.0:
        p.error("--row-hit-rate must be finite and between 0 and 1")
    if not np.isfinite(args.thermal_step_ps) or args.thermal_step_ps <= 0:
        p.error("--thermal-step-ps must be finite and positive")
    args.interconnect = args.interconnect or ("layout" if args.power_model == "spice-transient" else "none")
    if args.interconnect == "layout" and (args.power_model != "spice-transient" or args.mesh_method != "notebook"):
        p.error("--interconnect layout requires --power-model spice-transient and --mesh-method notebook")
    if not np.isfinite(args.interconnect_step_um) or args.interconnect_step_um <= 0:
        p.error("--interconnect-step-um must be finite and positive")
    if args.interconnect == "none" and args.interconnect_step_um != 0.05:
        p.error("--interconnect-step-um requires --interconnect layout")

    from mpi4py import MPI
    if MPI.COMM_WORLD.size != 1:
        p.error("This field-saving driver currently requires a single MPI rank")

    out_dir = Path(args.out_dir or (
        f"out/bitcell_transient_{args.power_model}_{args.point}" + ("_instantaneous" if args.instantaneous else "")))
    print(f"lateral boundary conditions: {args.lateral_bc} (x and y)")
    fields_dir = out_dir / "fields"
    spice_dir = out_dir / "spice"
    if ((fields_dir.exists() and (not fields_dir.is_dir() or any(fields_dir.iterdir())))
            or (out_dir / "power_workload.json").exists()
            or (spice_dir.exists() and (not spice_dir.is_dir() or any(spice_dir.iterdir())))):
        p.error("Output contains a prior run; choose a fresh --out-dir to preserve its results")
    out_dir.mkdir(parents=True, exist_ok=True)
    fields_dir.mkdir(exist_ok=True)

    pulse, workload, trace = None, None, None
    if args.power_model == "spice-transient":
        workload = build_spice_workload(
            args.point, row_hit_rate=args.row_hit_rate, period_ns=args.period_ns,
            pulse_width_ns=args.pulse_width_ns, spice_max_step_ps=args.spice_step_ps,
            out_dir=out_dir / "spice", interconnect=args.interconnect,
            interconnect_step_um=args.interconnect_step_um)
        trace = workload.trace
        # A nonzero per-device reference field validates spatial normalization;
        # in pulse mode it is NOT the actual (time-varying) source used below.
        device_power_active = ({name: energy / trace.time_s[-1]
                                for name, energy in workload.device_energy_j.items()}
                               if args.instantaneous else workload.device_average_power_w)
        print(f"SPICE event: {sum(workload.device_energy_j.values())*1e15:.6g} fJ; "
              f"period {workload.period_s*1e9:.6g} ns; row-hit rate {workload.row_hit_rate:g}")
        workload_metadata = dict(workload.metadata, thermal_solver_connected=True,
                                 application="single-access" if args.instantaneous else "sustained-average")
    elif args.instantaneous:
        pulse = named_access_pulse(args.point)
        device_power_active = pulse.device_power_w
        pulse_s = pulse.duration_s
        print(f"single-access mode: {pulse.total_energy_j*1e15:.6g} fJ, "
              f"one {pulse_s*1e9:.6g} ns energy-equivalent rectangle")
        print(pulse.description)
    else:
        device_power_w = named_bias_point_power_w(args.point, row_hit_rate=args.row_hit_rate)
        device_power_active = device_power_w
        pulse_s = None
        print(f"sustained mode: row_hit_rate={args.row_hit_rate:.4f}")
    if workload is None:
        workload_metadata = {"kind": "dc-surrogate", "point": args.point,
                             "access_energy_model_revision": ACCESS_ENERGY_MODEL_REVISION,
                             "spice_model_revision": SPICE_MODEL_REVISION,
                             "row_hit_rate": args.row_hit_rate,
                             "device_power_active_w": device_power_active}
    workload_path = out_dir / "power_workload.json"
    workload_path.write_text(json.dumps(workload_metadata, indent=2) + "\n")

    power_label = "reference event-mean" if trace is not None and args.instantaneous else "active"
    print(f"{power_label} per-instance power (W): {({k: f'{v:.3e}' for k, v in device_power_active.items()})}")

    mesh_data, registry, window = build_bitcell_mesh(
        device_power_active, out_dir, mesh_method=args.mesh_method,
        mesh_manifest=args.mesh_manifest, refine=args.refine)
    k, rho_cp, q_active = build_coeffs(mesh_data.mesh, mesh_data.cell_tags, registry, source_depth_m=None)
    source_audit = verify_device_source_powers(mesh_data, registry, q_active, device_power_active)
    combined_sources = None
    network = trace.metadata.get("interconnect_network") if trace is not None else None
    if network:
        from physics.interconnect_sources import CombinedHeatSources

        manifest_path = Path(args.mesh_manifest or out_dir / "sram_sp_cell_material_regions.json")
        manifest = json.loads(manifest_path.read_text())
        print("Mapping layout resistor losses into intersecting thermal tetrahedra", flush=True)
        combined_sources = CombinedHeatSources(mesh_data, registry, manifest, network)
        wire_power_active = ({name: energy / trace.time_s[-1]
                              for name, energy in workload.interconnect_energy_j.items()}
                             if args.instantaneous else workload.interconnect_average_power_w)
        q_active = combined_sources.set_powers(device_power_active, wire_power_active)
        source_audit = combined_sources.audit_powers(q_active, device_power_active, wire_power_active)
        (out_dir / "interconnect_projection.json").write_text(
            json.dumps(combined_sources.projection_report, indent=2) + "\n")
        print(f"Local interconnect/contact energy: {sum(workload.interconnect_energy_j.values())*1e15:.6g} fJ; "
              f"{len(wire_power_active)} resistors", flush=True)
    if trace is not None and args.instantaneous:
        source_audit["interpretation"] = "Event-mean spatial normalization only; actual load is time-varying"
    if mesh_data.mesh.comm.rank == 0:
        (out_dir / "source_power_audit.json").write_text(json.dumps(source_audit, indent=2))
    q_idle = q_active.x.array * 0.0  # Explicit zero-source cooldown; no invented idle activity.

    bcs = BoundaryConditions(
        ambient_t_k=300.0, backside_h_eff=20000.0, top_h_eff=None,
        periodic_x=args.lateral_bc == "periodic", periodic_y=args.lateral_bc == "periodic",
    )
    chip = types.SimpleNamespace(bcs=bcs)

    if args.instantaneous and trace is not None:
        from dolfinx.fem import Function

        edges, dt_access = spice_thermal_time_grid(trace, args.thermal_step_ps)
        sources = combined_sources or DeviceHeatSources(mesh_data, registry)
        deposited_density = Function(sources.q.function_space)
        solver = TransientHeatSolver(mesh_data, k, rho_cp, chip, dt=dt_access, T0=300.0)
        np.save(fields_dir / "dof_coords.npy", solver.V.tabulate_dof_coordinates())
        np.save(fields_dir / "connectivity.npy", solver.V.dofmap.list)
        times_s, tmax_hist, tmin_hist = [0.0], [300.0], [300.0]
        np.save(fields_dir / "T_000.npy", solver.T_prev.x.array.copy())
        step_powers, step_wire_powers = [], []
        wire_ids = sorted(trace.interconnect_power_w) if network else []
        for step_i, (start, end) in enumerate(zip(edges[:-1], edges[1:]), start=1):
            powers = trace.average_device_power_w(float(start), float(end))
            wire_powers = trace.average_interconnect_power_w(float(start), float(end)) if network else {}
            source = sources.set_powers(powers, wire_powers) if network else sources.set_powers(powers)
            T = solver.step(source.x.array, dt=dt_access)
            # Audit the actual DG0 array consumed by the solver, independently
            # of the intended device energies or input powers.
            deposited_density.x.array[:] += solver.q.x.array * dt_access
            times_s.append(float(end)); tmax_hist.append(tmax(T)[0])
            tmin_hist.append(float(T.x.array.min()))
            np.save(fields_dir / f"T_{step_i:03d}.npy", T.x.array.copy())
            step_powers.append([powers[f"X{i}"] for i in range(8)])
            step_wire_powers.append([wire_powers[name] for name in wire_ids])
            if step_i % 50 == 0 or step_i == len(edges) - 1:
                print(f"SPICE thermal access: {step_i}/{len(edges)-1} steps; "
                      f"t={end*1e9:.4f} ns, Tmax={tmax_hist[-1]:.6f} K", flush=True)
        active_end_s = t_s = float(edges[-1])
        energy_audit = (sources.audit_energy(deposited_density, workload.device_energy_j,
                                            workload.interconnect_energy_j) if network else
                        sources.audit_energy(deposited_density, workload.device_energy_j))
        energy_audit.update({"active_duration_s": active_end_s,
                             "active_step_count": len(edges)-1, "thermal_dt_s": dt_access,
                             "integration": "piecewise-linear SPICE energy averaged over each thermal step"})
        (out_dir / "source_energy_audit.json").write_text(json.dumps(energy_audit, indent=2) + "\n")
        np.savez_compressed(out_dir / "thermal_source_steps.npz", edges_s=edges,
                            device_ids=np.array([f"X{i}" for i in range(8)]),
                            device_power_w=np.asarray(step_powers),
                            resistor_ids=np.array(wire_ids, dtype=str),
                            interconnect_power_w=np.asarray(step_wire_powers))
        print(f"audited deposited SPICE energy: {energy_audit['deposited_total_j']:.12g} J", flush=True)
        for dt in _dt_schedule(N_IDLE_STEPS, dt0=dt_access * 2):
            T = solver.step(q_idle, dt=dt)
            t_s += dt
            step_i += 1
            times_s.append(t_s); tmax_hist.append(tmax(T)[0])
            tmin_hist.append(float(T.x.array.min()))
            np.save(fields_dir / f"T_{step_i:03d}.npy", T.x.array.copy())
        np.save(fields_dir / "tmin_hist.npy", np.asarray(tmin_hist))
        if min(tmin_hist) < 300.0 - 1e-3:
            print(f"WARNING: minimum T={min(tmin_hist):.6f} K below ambient. "
                  "Consistent-mass P1 discretization is not positivity-preserving; "
                  "interpret local extrema with mesh/timestep convergence checks.")
    elif args.instantaneous:
        # Resolve the prescribed rectangle with eight backward-Euler steps,
        # then relax with growing steps. Peak temperature remains dt-dependent.
        dt_pulse = pulse_s / 8
        solver = TransientHeatSolver(mesh_data, k, rho_cp, chip, dt=dt_pulse, T0=300.0)
        np.save(fields_dir / "dof_coords.npy", solver.V.tabulate_dof_coordinates())
        np.save(fields_dir / "connectivity.npy", solver.V.dofmap.list)
        times_s, tmax_hist = [0.0], [300.0]
        np.save(fields_dir / "T_000.npy", solver.T_prev.x.array.copy())
        t_s = 0.0
        step_i = 1
        n_pulse_steps = 8
        powered_steps_s = []
        for _ in range(n_pulse_steps):
            T = solver.step(q_active.x.array, dt=dt_pulse)
            powered_steps_s.append(dt_pulse)
            t_s += dt_pulse
            times_s.append(t_s); tmax_hist.append(tmax(T)[0])
            np.save(fields_dir / f"T_{step_i:03d}.npy", T.x.array.copy()); step_i += 1
        active_end_s = t_s
        energy_audit = verify_access_source_energy(pulse, source_audit, powered_steps_s)
        if mesh_data.mesh.comm.rank == 0:
            (out_dir / "source_energy_audit.json").write_text(json.dumps(energy_audit, indent=2))
        print(f"audited deposited access energy: {energy_audit['deposited_total_j']:.12g} J")
        for dt in _dt_schedule(N_IDLE_STEPS, dt0=dt_pulse * 2):
            T = solver.step(q_idle, dt=dt)
            t_s += dt
            times_s.append(t_s); tmax_hist.append(tmax(T)[0])
            np.save(fields_dir / f"T_{step_i:03d}.npy", T.x.array.copy()); step_i += 1
    else:
        solver = TransientHeatSolver(mesh_data, k, rho_cp, chip, dt=DT0_S, T0=300.0)
        np.save(fields_dir / "dof_coords.npy", solver.V.tabulate_dof_coordinates())
        np.save(fields_dir / "connectivity.npy", solver.V.dofmap.list)
        times_s, tmax_hist = [0.0], [300.0]
        np.save(fields_dir / "T_000.npy", solver.T_prev.x.array.copy())
        t_s = 0.0
        step_i = 1
        for dt in _dt_schedule(N_ACTIVE_STEPS):
            T = solver.step(q_active.x.array, dt=dt)
            t_s += dt
            times_s.append(t_s); tmax_hist.append(tmax(T)[0])
            np.save(fields_dir / f"T_{step_i:03d}.npy", T.x.array.copy()); step_i += 1
        active_end_s = t_s

        # P0.1 audit check (optimized-singing-creek.md): does q_active
        # deliver the intended per-device power on THIS mesh -- unverified
        # for the transient path until now.
        balance_options = ({"intended_total_w": source_audit["electrical_total_w"]} if network else {})
        print_power_balance(power_balance(mesh_data, registry, chip, T, k, q_active,
                                          source_depth_m=None, **balance_options),
                             check_robin=False)  # not yet at steady state -- see post/budget.py's docstring
        for dt in _dt_schedule(N_IDLE_STEPS):
            T = solver.step(q_idle, dt=dt)
            t_s += dt
            times_s.append(t_s); tmax_hist.append(tmax(T)[0])
            np.save(fields_dir / f"T_{step_i:03d}.npy", T.x.array.copy()); step_i += 1

    times_s = np.array(times_s)
    tmax_hist = np.array(tmax_hist)
    np.save(fields_dir / "times_s.npy", times_s)
    np.save(fields_dir / "tmax_hist.npy", tmax_hist)
    meta = {"active_end_s": active_end_s, "n_steps": len(times_s), "point": args.point,
            "instantaneous": args.instantaneous, "lateral_bc": args.lateral_bc,
            "mesh_method": args.mesh_method,
            "mesh_manifest": str(Path(args.mesh_manifest).resolve()) if args.mesh_manifest else
                (str((out_dir / "sram_sp_cell_material_regions.json").resolve())
                 if args.mesh_method == "notebook" else None),
            "source_mapping_sha256": mapping_revision(),
            "spice_model_revision": SPICE_MODEL_REVISION,
            "access_energy_model_revision": ACCESS_ENERGY_MODEL_REVISION,
            "thermal_power_revision": THERMAL_POWER_REVISION,
            "power_model": args.power_model,
            "interconnect_model": args.interconnect,
            "power_workload_path": str(workload_path.resolve()),
            "power_workload_sha256": hashlib.sha256(workload_path.read_bytes()).hexdigest(),
            "row_hit_rate": None if args.instantaneous else args.row_hit_rate,
            "device_power_active_w": device_power_active}
    if workload is not None:
        meta["spice_event"] = workload_metadata
        if args.instantaneous:
            meta["thermal_dt_s"] = dt_access
            meta["deposited_total_j"] = energy_audit["deposited_total_j"]
            meta["minimum_temperature_k"] = min(tmin_hist)
            meta["peak_temperature_k"] = float(tmax_hist.max())
    if pulse is not None:
        meta["access_pulse"] = {
            "description": pulse.description, "duration_s": pulse.duration_s,
            "period_s": pulse.period_s, "device_energy_j": pulse.device_energy_j,
            "expected_total_j": pulse.total_energy_j,
            "deposited_total_j": energy_audit["deposited_total_j"],
        }
    if meta["mesh_manifest"]:
        meta["mesh_manifest_sha256"] = hashlib.sha256(Path(meta["mesh_manifest"]).read_bytes()).hexdigest()
    (fields_dir / "meta.json").write_text(json.dumps(meta))
    print(f"saved {len(times_s)} field snapshots to {fields_dir}")
    if args.no_renders:
        return

    # Two-panel PHASE-RELATIVE plot: rise vs t, decay vs (t - active_end_s).
    # Fixes the "sudden jump" look -- a single absolute-log-time axis
    # compresses an entire ~60ms decay into a sliver next to a ~60ms rise
    # that ends at the SAME absolute time, even though both phases are
    # individually gradual.
    active_mask = times_s <= active_end_s
    idle_mask = ~active_mask
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    dT = tmax_hist - 300.0
    display_scale, display_unit = (1e9, "ns") if args.instantaneous else (1e3, "ms")
    active_plot_times = (times_s[active_mask] if args.instantaneous else
                         np.maximum(times_s[active_mask], times_s[1] if len(times_s) > 1 else 1e-9))
    ax1.plot(active_plot_times * display_scale,
             dT[active_mask], "o-", color="#B7410E", lw=2, ms=4)
    if not args.instantaneous:
        ax1.set_xscale("log")
    ax1.set_xlabel(f"time since workload start ({display_unit})"); ax1.set_ylabel("peak ΔT (K)")
    ax1.set_title("Single access: transient response" if args.instantaneous else "Active: rise toward steady state")
    ax1.grid(alpha=0.3, which="both")

    idle_t_rel = times_s[idle_mask] - active_end_s
    idle_t_rel = np.maximum(idle_t_rel, idle_t_rel[idle_t_rel > 0].min() if (idle_t_rel > 0).any() else 1e-9)
    ax2.plot(idle_t_rel * display_scale, dT[idle_mask], "o-", color="#2E5A88", lw=2, ms=4)
    ax2.set_xscale("log"); ax2.set_xlabel(f"time since workload stop ({display_unit})"); ax2.set_ylabel("peak ΔT (K)")
    ax2.set_title("Idle: relaxation toward ambient"); ax2.grid(alpha=0.3, which="both")
    fig.suptitle(f"Bitcell hotspot transient ({args.point}"
                 f"{', SPICE waveform' if args.instantaneous and trace is not None else ', surrogate pulse' if args.instantaneous else f', row_hit_rate={args.row_hit_rate:.3f}'})")
    fig.tight_layout()
    fig.savefig(out_dir / "tmax_vs_time.png", dpi=140)
    plt.close(fig)
    print(f"wrote {out_dir}/tmax_vs_time.png")

    # GIF: frames at uniform Tmax increments (not uniform step index) within
    # each phase, so the animation progresses smoothly instead of sitting
    # still then jumping.
    active_idx = [i for i in range(len(times_s)) if active_mask[i]]
    idle_idx = [i for i in range(len(times_s)) if idle_mask[i]]
    frame_idx = (
        [active_idx[i] for i in _select_uniform_dt_frames(tmax_hist[active_idx], N_RENDER_FRAMES_PER_PHASE)]
        + [idle_idx[i] for i in _select_uniform_dt_frames(tmax_hist[idle_idx], N_RENDER_FRAMES_PER_PHASE)]
    ) if len(idle_idx) > 1 else active_idx

    # Fixed slice location + fixed color scale, both computed ONCE from the
    # GLOBAL peak across the whole run, not per frame: verified directly
    # that the previous per-frame choices caused the "sudden change halfway
    # through" look reported -- (1) render_temperature_xy_slice's default
    # clim=None auto-scales each frame's colormap to THAT frame's own
    # min/max dT, so a barely-warmed idle frame gets stretched to the full
    # colormap just like the true peak frame, reading as an abrupt,
    # meaningless jump in color right at the active/idle switch even though
    # the physical temperature is changing smoothly; (2) z_um was
    # recomputed per frame from that frame's own argmax location, which can
    # shift between layers as the peak cools/relaxes, jumping the slice
    # plane itself out from under the animation.
    dof_coords_arr = np.load(fields_dir / "dof_coords.npy")
    global_peak_i = int(np.argmax(tmax_hist))
    T_peak_arr = np.load(fields_dir / f"T_{global_peak_i:03d}.npy")
    z_um_fixed = dof_coords_arr[int(np.argmax(T_peak_arr)), 2] * 1e6
    # NOTE: the plotted scalar is dT = T - 300 (see mesh/viz3d.py's
    # _temperature_grid), not absolute T -- clim must be in THAT frame
    # (0..peak dT), not (300..peak T), or every frame's data (0-31K) sits
    # far below a (300, 331)-style clim and clamps to solid black.
    clim = (0.0, float(tmax_hist.max() - 300.0))

    from dolfinx.fem import Function
    frame_paths = []
    for i in frame_idx:
        T_arr = np.load(fields_dir / f"T_{i:03d}.npy")
        tk = float(T_arr.max())
        # Reuse render_temperature_xy_slice by wrapping the raw array back
        # into a Function on the solver's own V (cheap, same mesh throughout).
        T_fn = Function(solver.V)
        T_fn.x.array[:] = T_arr
        label = "active" if i in active_idx else "idle"
        frame_path = out_dir / f"frame_{len(frame_paths):03d}.png"
        render_temperature_xy_slice(T_fn, z_um_fixed, f"t={times_s[i]*display_scale:.4f}{display_unit} ({label}) Tmax={tk:.3f}K",
                                     str(frame_path), clim=clim)
        frame_paths.append(frame_path)

    frames = [Image.open(p_).convert("RGB") for p_ in frame_paths]
    gif_path = out_dir / "hotspot_evolution.gif"
    frames[0].save(gif_path, save_all=True, append_images=frames[1:], duration=150, loop=0)
    print(f"wrote {gif_path} ({len(frames)} frames)")


if __name__ == "__main__":
    main()
